import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    inject: ['/tmp/transformers-shim.js'], // Inject shim for transformers.js
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins
    ],
    format: "cjs",
    target: "es2020",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "dist/main.js",
    minify: prod,
    platform: "browser", // Use browser platform to avoid Node.js-specific code paths
    mainFields: ["browser", "module", "main"], // Prefer browser field for browser-compatible builds
    conditions: ["browser", "import"], // Use browser conditions
    define: {
        'global': 'globalThis', // Use globalThis for better compatibility
        'import.meta.url': '"file:///"', // Provide a dummy import.meta.url for bundled ESM
        'process.env.NODE_ENV': '"production"', // Define NODE_ENV
    },
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}